languages = {
	check = "english"
}

filter = {
    show_vanilla = no
    show_loaded_mods = no

    trigger = {
        NOR = {
            file = common/script_values/bpm_cabpos_values.txt # weird 3.0 merge
            file = common/scripted_effects/bpm_pulse_effects.txt # weird 3.0 merge
            text = "unknown field `disallowing_amendments`" # tiger bug
            text = "amendment scope:amendment_type" # tiger bug
            key = image-size # fake and gay
            text = "expects scope:actor to be character but scope:actor seems to be country" # tiger bug i'm pretty sure
            text = "`modifier` is redefined in a following line" # this is fine also it's a common pattern with INJECT: so i'm ignoring it
            text = "`acceptance_modifier` is redefined in a following line" # this also works
            text = "`institution_modifier` is redefined in a following line" # also works
            text = "`tax_modifier_very_low` is redefined in a following line"
            text = "`tax_modifier_low` is redefined in a following line"
            text = "`tax_modifier_medium` is redefined in a following line"
            text = "`tax_modifier_high` is redefined in a following line"
            text = "`tax_modifier_very_high` is redefined in a following line"
            # doing this with on_enact DOES NOT WORK that's a real error
            text = "missing english localization key bpm_minister_of_" # hacky cabinet stuff
            
            OR = { #VANILLA BUGS
                text = "state_free_state_pop_support_movement_anti_slavery_mult_desc"
                text = "dp_annex_war_desc"
                text = "dp_taiping_rebellion_desc"
                #AND = {
                #    OR = {
                #        key = missing-localization
                #    }
                #    OR = {
                #        file = "common/history/characters/*"
                #    }
                #}
            }
        
        # In short, valid trigger keys are:
        # - always = yes/no
        # - NOT, AND, OR, NAND, NOR
        # - severity
        # - confidence
        # - key
        # - file
        # - text
        # - ignore_keys_in_files
        }
    }
}

# Sometimes vic3-tiger makes a mistake in determining the scope types expected
# by a scripted trigger or effect. Its conclusions can be overridden here.
# Scope overrides can be ALL (to accept any scope) or a list separated by |,
# like character|province|landed_title
scope_override = {
}

# Optional block to control output styles and colors. Colors are enabled by default.
# Another way to disable all ANSI characters in the output is to supply the --no-color flag.
# That flag will override anything you define here, in the config file.
output_style = {
    # Default value is 'yes', except with vic3-tiger-auto when it is default 'no'.
    # If set to 'no', no ANSI characters will be added to the output and the output will not be colored.
    # Also, all other settings in this block will be ignored.
#    enable = yes

    # Optional block to set the error color.
#    error = {
#        # Default is red. Supported values are Black, Red, Green, Yellow, Blue, Purple, Cyan, White.
#        color = "red"
#    }
    # Optional block to set the warning color.
#    warning = {
#        # Default is yellow. Supported values are Black, Red, Green, Yellow, Blue, Purple, Cyan, White.
#        color = "yellow"
#    }
    # Optional block to set the info color.
#    info = {
#        # Default is green. Supported values are Black, Red, Green, Yellow, Blue, Purple, Cyan, White.
#        color = "green"
#    }
    # Optional block to set the advice color.
#    untidy = {
#        # Default is cyan. Supported values are Black, Red, Green, Yellow, Blue, Purple, Cyan, White.
#        color = "cyan"
#    }

}