l_japanese:
 # BASE/MISC
 BPM_VALUE_BASE:0 "Base value"

 BPM_VALUE_FROM_NO_TECH_MASS_COMMS:0 "no Mass Communication [Concept('concept_technology', 'Tech')]"

 # LAW/INSTITUTION
 BPM_VALUE_FROM_LAW_MONARCHY:0 "[Concept('concept_law', 'Law')] [GetLawType('law_monarchy').GetName]"
 BPM_VALUE_FROM_LAW_TRADITIONALISM:0 "[Concept('concept_law', 'Law')] [GetLawType('law_traditionalism').GetName]"
 BPM_VALUE_FROM_LAW_PEASANT_LEVIES:0 "[Concept('concept_law', 'Law')] [GetLawType('law_peasant_levies').GetName]"
 BPM_VALUE_FROM_LAW_SERFDOM:0 "[Concept('concept_law', 'Law')] [GetLawType('law_serfdom').GetName]"
 BPM_VALUE_FROM_LAW_TENANT_FARMERS:0 "[Concept('concept_law', 'Law')] [GetLawType('law_tenant_farmers').GetName]"
 BPM_VALUE_FROM_LAW_ISOLATIONISM:0 "[Concept('concept_law', 'Law')] [GetLawType('law_isolationism').GetName]"
 BPM_VALUE_FROM_LAW_NO_ELECTIONS:0 "[Concept('concept_law', 'Law')] No [Concept('concept_election', 'Elections')]"
 BPM_VALUE_FROM_LAW_OUTLAWED_DISSENT:0 "[Concept('concept_law', 'Law')] [GetLawType('law_outlawed_dissent').GetName]"
 BPM_VALUE_FROM_LAW_CENSORSHIP:0 "[Concept('concept_law', 'Law')] [GetLawType('law_censorship').GetName]"
 BPM_VALUE_FROM_LAW_PROTECTED_SPEECH:0 "[Concept('concept_law', 'Law')] [GetLawType('law_protected_speech').GetName]"
 BPM_VALUE_FROM_LAW_ANARCHY:0 "[Concept('concept_law', 'Law')] [GetLawType('law_anarchy').GetName]"
 BPM_VALUE_FROM_LAW_AD_HOC_CENTRALIZATION:0 "[Concept('concept_law', 'Law')] [GetLawType('law_ad_hoc_centralization').GetName]"
 BPM_VALUE_FROM_INSTITUTION_LOCAL_POLICE:0 "[Concept('concept_institution', 'Institution')] investment in [GetLawType('law_local_police').GetName]"
 BPM_VALUE_FROM_INSTITUTION_NATIONAL_POLICE:0 "[Concept('concept_institution', 'Institution')] investment in [GetLawType('law_dedicated_police').GetName]"
 BPM_VALUE_FROM_INSTITUTION_MILITARIZED_POLICE:0 "[Concept('concept_institution', 'Institution')] investment in [GetLawType('law_militarized_police').GetName]"
 BPM_VALUE_FROM_INSTITUTION_ELECTED_POLICE:0 "[Concept('concept_institution', 'Institution')] investment in [GetLawType('law_elected_police').GetName]"
 BPM_VALUE_FROM_INSTITUTION_NATIONAL_GUARD:0 "[Concept('concept_institution', 'Institution')] investment in [GetLawType('law_national_guard').GetName]"
 BPM_VALUE_FROM_INSTITUTION_SECRET_POLICE:0 "[Concept('concept_institution', 'Institution')] investment in [GetLawType('law_secret_police').GetName]"
 BPM_VALUE_FROM_INSTITUTION_GUARANTEED_LIBERTIES:0 "[Concept('concept_institution', 'Institution')] investment with [GetLawType('law_guaranteed_liberties').GetName]"
 BPM_VALUE_FROM_INSTITUTION_SUFFRAGE:0 "[Concept('concept_institution', 'Institution')] investment in [GetInstitutionType('institution_suffrage').GetName]"

 # CURRENT STATUS
 BPM_VALUE_FROM_RADICALS:0 "[Concept('concept_radical', 'Radicals')]"
 BPM_VALUE_FROM_LOYALISTS:0 "[Concept('concept_loyalist', 'Loyalists')]"
 BPM_VALUE_FROM_WAR:0 "[Concept('concept_war_support', 'War Support')]"
 BPM_VALUE_FROM_WAR_HIGH_SUPPORT:0 "High [Concept('concept_war_support', 'War Support')]"
 BPM_VALUE_FROM_WAR_MEDIUM_SUPPORT:0 "Medium [Concept('concept_war_support', 'War Support')]"
 BPM_VALUE_FROM_WAR_LOW_SUPPORT:0 "Low [Concept('concept_war_support', 'War Support')]"
 BPM_VALUE_FROM_WAR_VERY_LOW_SUPPORT:0 "Very Low [Concept('concept_war_support', 'War Support')]"
 BPM_VALUE_FROM_REVOLUTION:0 "Ongoing [Concept('concept_revolution', 'Revolution')]"
 BPM_VALUE_FROM_INSURRECTION:0 "Insurrectionary [Concept('concept_interest_group', 'Interest Groups')]"
 BPM_VALUE_FROM_ELECTION:0 "Ongoing [Concept('concept_election', 'Election')]"
 BPM_VALUE_FROM_LOW_LEGITIMACY:0 "Low (below 30) [Concept('concept_legitimacy', 'Legitimacy')]"
 BPM_VALUE_FROM_VERY_LOW_LEGITIMACY:0 "Very low (below 10) [Concept('concept_legitimacy', 'Legitimacy')]"
 BPM_VALUE_FROM_ENTRENCHED_INTEREST_GROUPS:0 "Every year the current ruling [Concept('concept_interest_group', 'Interest Groups')] spent in government"

	# WAR
 BPM_STABILITY_FROM_WAR_BASE:0 "#gold Ongoing War#! Base Value"
 BPM_STABILITY_FROM_WAR_OCCUPATION:0 "#gold Ongoing War#! Enemy Occupation"
 BPM_STABILITY_FROM_WAR_CASUALTIES:0 "#gold Ongoing War#! Casualties"