l_turkish:
 # TEMEL/ÇEŞİTLİ
 BPM_VALUE_BASE:0 "Temel değer"
 BPM_VALUE_RANDOM:0 "Rastgele değer"

 BPM_VALUE_FROM_NO_TECH_MASS_COMMS:0 "Kitle İletişimi [Concept('concept_technology', 'Teknolojisi')] yok"

 # YASA/KURUM
 BPM_VALUE_FROM_LAW_MONARCHY:0 "[GetLawType('law_monarchy').GetName] [Concept('concept_law', 'Yasası')]"
 BPM_VALUE_FROM_LAW_TRADITIONALISM:0 "[GetLawType('law_traditionalism').GetName] [Concept('concept_law', 'Yasası')]"
 BPM_VALUE_FROM_LAW_AGRARIANISM:0 "[GetLawType('law_agrarianism').GetName] [Concept('concept_law', 'Yasası')]"
 BPM_VALUE_FROM_LAW_LAISSEZ_FAIRE:0 "[GetLawType('law_laissez_faire').GetName] [Concept('concept_law', 'Yasası')]"
 BPM_VALUE_FROM_LAW_INTERVENTIONISM:0 "[GetLawType('law_interventionism').GetName] [Concept('concept_law', 'Yasası')]"
 BPM_VALUE_FROM_LAW_HOMESTEADING:0 "[GetLawType('law_homesteading').GetName] [Concept('concept_law', 'Yasası')]"
 BPM_VALUE_FROM_LAW_PEASANT_LEVIES:0 "[GetLawType('law_peasant_levies').GetName] [Concept('concept_law', 'Yasası')]"
 BPM_VALUE_FROM_LAW_SERFDOM:0 "[GetLawType('law_serfdom').GetName] [Concept('concept_law', 'Yasası')]"
 BPM_VALUE_FROM_LAW_TENANT_FARMERS:0 "[GetLawType('law_tenant_farmers').GetName] [Concept('concept_law', 'Yasası')]"
 BPM_VALUE_FROM_LAW_COMMERCIALIZED_AGRICULTURE:0 "[GetLawType('law_commercialized_agriculture').GetName] [Concept('concept_law', 'Yasası')]"
 BPM_VALUE_FROM_LAW_ISOLATIONISM:0 "[GetLawType('law_isolationism').GetName] [Concept('concept_law', 'Yasası')]"
 BPM_VALUE_FROM_LAW_UNREGULATED_WORK_TIME:0 "[GetLawType('law_unregulated_work_time').GetName] [Concept('concept_law', 'Yasası')]"
 BPM_VALUE_FROM_LAW_NO_WORKERS_RIGHTS:0 "[GetLawType('law_no_workers_rights').GetName] [Concept('concept_law', 'Yasası')]"
 BPM_VALUE_FROM_LAW_NO_WELFARE:0 "[GetLawType('law_no_social_security').GetName] [Concept('concept_law', 'Yasası')]"
 BPM_VALUE_FROM_LAW_POOR_LAWS:0 "[GetLawType('law_poor_laws').GetName] [Concept('concept_law', 'Yasası')]"
 BPM_VALUE_FROM_LAW_NO_ELECTIONS:0 "[Concept('concept_election', 'Seçim')] [Concept('concept_law', 'Yasası')] Yok"
 BPM_VALUE_FROM_LAW_NO_FULL_DEMOCRACY:0 "Tam Oy Hakkı yatırımlı [GetLawType('law_universal_suffrage').GetName] [Concept('concept_law', 'Yasası')] Yok"
 BPM_VALUE_FROM_LAW_OUTLAWED_DISSENT:0 "[GetLawType('law_outlawed_dissent').GetName] [Concept('concept_law', 'Yasası')]"
 BPM_VALUE_FROM_LAW_SOCIALIST_BAN:0 "[GetLawType('law_party_anti_socialist').GetName] [Concept('concept_law', 'Yasası')]"
 BPM_VALUE_FROM_LAW_CENSORSHIP:0 "[GetLawType('law_censorship').GetName] [Concept('concept_law', 'Yasası')]"
 BPM_VALUE_FROM_LAW_TRADITIONAL_OSTRACISM:0 "[GetLawType('law_traditional_ostracism').GetName] [Concept('concept_law', 'Yasası')]"
 BPM_VALUE_FROM_RIGHT_WING_APPROVAL: "[Concept('concept_bpm_ig_is_right_wing', 'Sağ Kanat Çıkar Gruplarının')] [concept_clout] ve [concept_approval] değerlerinden"
 BPM_VALUE_FROM_LAW_PROTECTED_SPEECH:0 "[GetLawType('law_protected_speech').GetName] [Concept('concept_law', 'Yasası')]"
 BPM_VALUE_FROM_LAW_ANARCHY:0 "[GetLawType('law_anarchy').GetName] [Concept('concept_law', 'Yasası')]"
 BPM_VALUE_FROM_LAW_AD_HOC_CENTRALIZATION:0 "[GetLawType('law_ad_hoc_centralization').GetName] [Concept('concept_law', 'Yasası')]"
 BPM_VALUE_FROM_LAW_STATE_RELIGION:0 "[GetLawType('law_state_religion').GetName] [Concept('concept_law', 'Yasası')]"
 BPM_VALUE_FROM_LAW_STATE_ATHEISM:0 "[GetLawType('law_state_atheism').GetName] [Concept('concept_law', 'Yasası')]"
 BPM_VALUE_FROM_LAW_NO_MULTICULTURALISM:0 "[GetLawType('law_multicultural').GetName] [Concept('concept_law', 'Yasası')] Yok"
 BPM_VALUE_FROM_INSTITUTION_LOCAL_POLICE:0 "[GetLawType('law_local_police').GetName] [Concept('concept_institution', 'Kurumuna')] yatırım"
 BPM_VALUE_FROM_INSTITUTION_NATIONAL_POLICE:0 "[GetLawType('law_dedicated_police').GetName] [Concept('concept_institution', 'Kurumuna')] yatırım"
 BPM_VALUE_FROM_INSTITUTION_MILITARIZED_POLICE:0 "[GetLawType('law_militarized_police').GetName] [Concept('concept_institution', 'Kurumuna')] yatırım"
 BPM_VALUE_FROM_INSTITUTION_ELECTED_POLICE:0 "[GetLawType('law_elected_police').GetName] [Concept('concept_institution', 'Kurumuna')] yatırım"
 BPM_VALUE_FROM_INSTITUTION_NATIONAL_GUARD:0 "[GetLawType('law_national_guard').GetName] [Concept('concept_institution', 'Kurumuna')] yatırım"
 BPM_VALUE_FROM_INSTITUTION_SECRET_POLICE:0 "[GetLawType('law_secret_police').GetName] [Concept('concept_institution', 'Kurumuna')] yatırım"
 BPM_VALUE_FROM_INSTITUTION_GUARANTEED_LIBERTIES:0 "[GetLawType('law_guaranteed_liberties').GetName] ile [Concept('concept_institution', 'Kuruma')] yatırım"
 BPM_VALUE_FROM_INSTITUTION_SUFFRAGE:0 "[GetInstitutionType('institution_suffrage').GetName] [Concept('concept_institution', 'Kurumuna')] yatırım"
 BPM_VALUE_FROM_INSTITUTION_CENSORSHIP:0 "[GetLawType('law_censorship').GetName] [Concept('concept_institution', 'Kurumuna')] yatırım"
 BPM_VALUE_FROM_INSTITUTION_OUTLAWED_DISSENT:0 "[GetLawType('law_outlawed_dissent').GetName] [Concept('concept_institution', 'Kurumuna')] yatırım"
 BPM_VALUE_FROM_INSTITUTION_RIGHT_OF_ASSEMBLY:0 "[GetLawType('law_right_of_assembly').GetName] [Concept('concept_institution', 'Kurumuna')] yatırım"

 # TEKRARLANABİLİR YASALAR
 BPM_VALUE_FROM_REPEATABLE_LAW_POLITICS_TERROR:0 "[GetLawType('law_repeatable_politics_great_terror').GetName] [Concept('concept_bpm_repeatable_law', '$concept_bpm_repeatable_law$')]"

 # MEVCUT DURUM
 BPM_VALUE_FROM_RADICALS:0 "[Concept('concept_radical', 'Radikaller')]"
 BPM_VALUE_FROM_LOYALISTS:0 "[Concept('concept_loyalist', 'Sadıklar')]"
 BPM_VALUE_FROM_WAR:0 "[Concept('concept_war_support', 'Savaş Desteği')]"
 BPM_VALUE_FROM_WAR_HIGH_SUPPORT:0 "Yüksek [Concept('concept_war_support', 'Savaş Desteği')]"
 BPM_VALUE_FROM_WAR_MEDIUM_SUPPORT:0 "Orta [Concept('concept_war_support', 'Savaş Desteği')]"
 BPM_VALUE_FROM_WAR_LOW_SUPPORT:0 "Düşük [Concept('concept_war_support', 'Savaş Desteği')]"
 BPM_VALUE_FROM_WAR_VERY_LOW_SUPPORT:0 "Çok Düşük [Concept('concept_war_support', 'Savaş Desteği')]"
 BPM_VALUE_FROM_REVOLUTION:0 "Devam Eden [Concept('concept_revolution', 'Devrim')]"
 BPM_VALUE_FROM_INSURRECTION:0 "Mayalanan [Concept('concept_revolution', 'Devrim')]"
 BPM_VALUE_FROM_INSURRECTION_CLOUT:0 "İsyancı [concept_interest_group] [concept_clout]"
 BPM_VALUE_FROM_ELECTION:0 "Devam Eden [Concept('concept_election', 'Seçim')]"
 BPM_VALUE_FROM_LOW_LEGITIMACY:0 "Düşük (30 altı) [Concept('concept_legitimacy', 'Meşruiyet')]"
 BPM_VALUE_FROM_VERY_LOW_LEGITIMACY:0 "Çok Düşük (10 altı) [Concept('concept_legitimacy', 'Meşruiyet')]"
 BPM_VALUE_FROM_ENTRENCHED_INTEREST_GROUPS:0 "Mevcut iktidardaki [Concept('concept_interest_group', 'Çıkar Gruplarının')] [concept_in_government] geçirdiği her yıl"
 BPM_VALUE_FROM_RIGIDITY:0 "[Concept('concept_bpm_political_stability', '$concept_bpm_political_stability$')]"
 BPM_VALUE_FROM_PEASANT_POPULATION:0 "[GetPopType('peasants').GetName] Nüfusu"
 BPM_VALUE_FROM_LABORER_POPULATION:0 "[GetPopType('laborers').GetName] Nüfusu"
 BPM_VALUE_FROM_MACHINIST_POPULATION:0 "[GetPopType('machinists').GetName]"
 BPM_VALUE_FROM_PEASANT_RADICALS:0 "[concept_radical] [GetPopType('peasants').GetName] Poplarından"
 BPM_VALUE_FROM_LABORER_RADICALS:0 "[concept_radical] [GetPopType('laborers').GetName] Poplarından"
 BPM_VALUE_FROM_MACHINIST_RADICALS:0 "[concept_radical] [GetPopType('machinists').GetName] Poplarından"
 BPM_VALUE_FROM_LABORER_LOYALISTS:0 "[concept_loyalist] [GetPopType('laborers').GetName] Poplarından"
 BPM_VALUE_FROM_MACHINIST_LOYALISTS:0 "[concept_loyalist] [GetPopType('machinists').GetName] Poplarından"
 BPM_VALUE_FROM_SYNDICALISM_DEVELOPMENT:0 "#yellow $je_bpm_syndicalism$#! Günlük Kaydı İlerlemesi"
 BPM_VALUE_FROM_AGRARIAN_SOCIALISM_DEVELOPMENT:0 "#yellow $je_bpm_agrarian_socialism$#! Günlük Kaydı İlerlemesi"
 BPM_VALUE_FROM_SOCS_POPULARITY:0 "[GetInterestGroupVariant('ig_socialists', GetPlayer).GetName] Popülaritesinden"
 BPM_VALUE_FROM_REVSOCS_POPULARITY:0 "[GetInterestGroupVariant('ig_revolutionist_socialists', GetPlayer).GetName] Popülaritesinden"
 BPM_VALUE_FROM_REFSOCS_POPULARITY:0 "[GetInterestGroupVariant('ig_reformist_socialists', GetPlayer).GetName] Popülaritesinden"
 BPM_VALUE_FROM_TRADE_UNIONS_POPULARITY:0 "[GetInterestGroupVariant('ig_trade_unions', GetPlayer).GetName] Popülaritesinden"
 BPM_VALUE_FROM_RURAL_FOLK_POPULARITY:0 "[GetInterestGroupVariant('ig_rural_folk', GetPlayer).GetName] Popülaritesinden"
 BPM_VALUE_FROM_INTELLIGENTSIA_POPULARITY:0 "[GetInterestGroupVariant('ig_intelligentsia', GetPlayer).GetName] Popülaritesinden"
 BPM_VALUE_FROM_NATLIBS_POPULARITY:0 "[GetInterestGroupVariant('ig_national_liberals', GetPlayer).GetName] Popülaritesinden"
 BPM_VALUE_FROM_LIBS_POPULARITY:0 "[GetInterestGroupVariant('ig_liberals', GetPlayer).GetName] Popülaritesinden"
 BPM_VALUE_FROM_INDUSTRIALISTS_POPULARITY:0 "[GetInterestGroupVariant('ig_industrialists', GetPlayer).GetName] Popülaritesinden"
 BPM_VALUE_FROM_PETTY_BOURGEOISIE_POPULARITY:0 "[GetInterestGroupVariant('ig_petty_bourgeoisie', GetPlayer).GetName] Popülaritesinden"
 BPM_VALUE_FROM_ARMED_FORCES_POPULARITY:0 "[GetInterestGroupVariant('ig_armed_forces', GetPlayer).GetName] Popülaritesinden"
 BPM_VALUE_FROM_RADS_POPULARITY:0 "[GetInterestGroupVariant('ig_radicals', GetPlayer).GetName] Popülaritesinden"
 BPM_VALUE_FROM_REC:0 "Stalwart'a Yönelik Afrikalı-Amerikalı Desteğinden"

 # ÇIKAR GRUPLARI VE KARAKTERLER
 BPM_VALUE_POWERFUL_ANARCHISTS:0 "Güçlü Anarşistler"
 BPM_VALUE_BOLSTERED_ANARCHISTS:0 "Desteklenmiş Anarşistler"
 BPM_VALUE_ANARCHIST_AGITATORS:0 "Anarşist [Concept('concept_agitator', 'Ajitatörler')]"
 BPM_VALUE_FROM_MONARCH_POPULARITY:0 "[Concept('concept_ruler', 'Monark')] [Concept('concept_popularity', 'Popülaritesi')] ([GetPlayer.GetRuler.GetFullName])"
 BPM_VALUE_FROM_MONARCH_POPULARITY_NEGATIVE:0 "Negatif [Concept('concept_ruler', 'Monark')] [Concept('concept_popularity', 'Popülaritesi')] ([GetPlayer.GetRuler.GetFullName])"
 BPM_VALUE_FROM_N_LEADER_AND_AGITATORS:0 "Şunun [Concept('concept_leader', 'Lideri')] ve [Concept('concept_agitator', 'Ajitatörlerinin')] [Concept('concept_popularity', 'Popülaritesi')]:"
 BPM_VALUE_FROM_CONSERVATIVE_LEADER_AND_AGITATORS:0 "$BPM_VALUE_FROM_N_LEADER_AND_AGITATORS$ [GetInterestGroupVariant('ig_conservatives',GetPlayer).GetName]"
 BPM_VALUE_FROM_REACTIONARY_LEADER_AND_AGITATORS:0 "$BPM_VALUE_FROM_N_LEADER_AND_AGITATORS$ [GetInterestGroupVariant('ig_reactionaries',GetPlayer).GetName]"
 BPM_VALUE_FROM_LIBERAL_LEADER_AND_AGITATORS:0 "$BPM_VALUE_FROM_N_LEADER_AND_AGITATORS$ [GetInterestGroupVariant('ig_liberals',GetPlayer).GetName]"
 BPM_VALUE_FROM_RADICAL_LEADER_AND_AGITATORS:0 "$BPM_VALUE_FROM_N_LEADER_AND_AGITATORS$ [GetInterestGroupVariant('ig_radicals',GetPlayer).GetName]"
 BPM_VALUE_FROM_SOCIALIST_LEADER_AND_AGITATORS:0 "$BPM_VALUE_FROM_N_LEADER_AND_AGITATORS$ [GetInterestGroupVariant('ig_socialists',GetPlayer).GetName]"
 BPM_VALUE_FROM_AGRARIAN_SOCIALIST_CHARACTERS:0 "[GetIdeology('ideology_eco_agrarian_socialist').GetName] Karakterlerinden"
 BPM_VALUE_FROM_SYNDICALIST_CHARACTERS:0 "[GetIdeology('ideology_dop_syndicalist').GetName] Karakterlerinden"

 # GÜNLÜK KAYDINA ÖZEL (JOURNAL SPECIFIC)
 BPM_VALUE_FROM_JOURNAL_PROGRESS:0 "Günlük Kaydı İlerlemesi"
 BPM_VALUE_JOURNAL_DURATION:0 "Günlük Kaydı Süresi"
 BPM_VALUE_FROM_PREV_BOMBS:0 "Önceki bombalamalardan"
 BPM_VALUE_FROM_POTD_CONVICTION:0 "#pink İnancın Gücünden#!"
 BPM_VALUE_POTD_ENDED_IN_GP:0 "#N Eylem Propagandası#! bir [concept_great_power] içinde sona erdi"
 BPM_VALUE_FROM_SYNDICALISM_LEGITIMIZED:0 "Meşrulaştırılmış Sendikalizm"
 BPM_VALUE_FROM_FAILED_SYNDICALIST_STRIKES:0 "Başarısız Sendikalist Grevlerden"

 BPM_VALUE_FROM_NO_TECH_ANARCHISM:0 "#yellow $anarchism$#! araştırılmadı"
 BPM_VALUE_FROM_SOCIALIST_IGS_POPULARITY:0 "[Concept('concept_bpm_ig_is_socialist','Sosyalist Çıkar Grupları')] Nüfusu"
 BPM_VALUE_FROM_SOCIALISTS_APPROVAL_POPULARITY:0 "[Concept('concept_bpm_ig_is_socialist','Sosyalist Çıkar Grupları')] Nüfusu ve [Concept('concept_approval','Memnuniyetsizliği')]"
 BPM_VALUE_FROM_TRADE_UNION_POPULARITY:0 "[GetInterestGroupVariant('ig_trade_unions', GetPlayer).GetName] Nüfusu"
 BPM_VALUE_FROM_TRADE_UNIONS_APPROVAL_POPULARITY:0 "[GetInterestGroupVariant('ig_trade_unions', GetPlayer).GetName] Nüfusu ve [Concept('concept_approval','Memnuniyetsizliği')]"
 BPM_VALUE_FROM_TRADE_UNION_CLOUT:0 "[GetInterestGroupVariant('ig_trade_unions', GetPlayer).GetName] [concept_clout]"
 BPM_VALUE_FROM_TRADE_UNIONS_APPROVAL_CLOUT:0 "[GetInterestGroupVariant('ig_trade_unions', GetPlayer).GetName] [concept_clout] ve [Concept('concept_approval','Memnuniyetsizliği')]"
 BPM_VALUE_FROM_POPULAR_ANGRY_TRADE_UNIONS:0 "$ig_approval_angry$ [GetInterestGroupVariant('ig_trade_unions', GetPlayer).GetName]"
 BPM_VALUE_FROM_ONGOING_LIBERAL_REVOLUTION:0 "Devam Eden [concept_bpm_ig_is_liberal] [concept_revolution]"
 BPM_VALUE_FROM_ONGOING_SOCIALIST_REVOLUTION:0 "Devam Eden [concept_bpm_ig_is_socialist] [concept_revolution]"
 BPM_VALUE_FROM_law_corporatized_unions:0 "[GetLawType('law_corporatized_unions').GetName]"
 BPM_VALUE_FROM_law_anti_strike_laws:0 "[GetLawType('law_anti_strike_laws').GetName]"
 BPM_VALUE_REVOLUTIONIST_SOCIALISTS_IN_GOVERNMENT:0 "[GetInterestGroupVariant('ig_revolutionist_socialists', GetPlayer).GetName] [concept_in_government]"
 BPM_VALUE_REFORMIST_SOCIALISTS_IN_GOVERNMENT:0 "[GetInterestGroupVariant('ig_reformist_socialists', GetPlayer).GetName] [concept_in_government]"
 BPM_VALUE_SOCIALISTS_IN_GOVERNMENT:0 "[GetInterestGroupVariant('ig_socialists', GetPlayer).GetName] [concept_in_government]"
 BPM_VALUE_STRIKE_EXHAUSTION:0 "Grevcilerin #blue Tükenmişlik seviyesi#!"
 BPM_VALUE_FROM_NO_GOAL:0 "Grevin bir hedefi yok"
 BPM_VALUE_FROM_CONTENT_LABOR_IGS:0 "Bir veya daha fazla [Concept('concept_bpm_ig_is_labor', 'Emek Çıkar Grubunun')] [concept_approval] değeri pozitif"
 BPM_MAX_EXHAUSTION_RATE_IN_REVOLUTION:0 "Aktif bir [concept_revolution] içinde #blue Tükenmişlik#! oranı sınırlandırıldı"
 BPM_VALUE_FROM_RETREATING_STRIKERS:0 "#P Grevciler geri çekiliyor!#!"
 BPM_VALUE_FROM_PRO_CONSERVATIVE_LAW_PASSING:0 "Bu Günlük Kaydı başladığından beri [GetInterestGroupVariant('ig_conservatives', GetPlayer).GetName] tarafından tercih edilen [Concept('concept_law', 'Yasalar')] geçti"
 BPM_VALUE_FROM_PRO_MODERNIZER_LOBBY_APPEASEMENT:0 "$bpm_je_all_modernizers$ tarafından kayırılan [Concept('concept_political_lobby', 'Siyasi Lobilerin')] [Concept('concept_political_lobby_appeasement', 'Yatıştırılması')]"
 BPM_VALUE_FROM_PRO_MODERNIZER_LAW_PASSING:0 "Bu Günlük Kaydı başladığından beri [GetInterestGroupVariant('ig_liberals', GetPlayer).GetName] veya [GetInterestGroupVariant('ig_radicals', GetPlayer).GetName] tarafından tercih edilen [Concept('concept_law', 'Yasalar')] geçti"
 BPM_VALUE_FROM_PRO_CONSERVATIVE_REPEATABLE_LAWS:0 "Şu [Concept('concept_bpm_repeatable_law', 'Tekrarlanabilir Yasalar')] şu anda aktif: [GetLawType('law_repeatable_religion_anti_secular_reaction').GetName], [GetLawType('law_repeatable_military_parades_and_drills').GetName], [GetLawType('law_repeatable_culture_promote_absolutist_values').GetName] ve [GetLawType('law_repeatable_religion_promote_state_religion').GetName]"
 BPM_VALUE_FROM_PRO_LIBERAL_REPEATABLE_LAWS:0 "Aşağıdaki [Concept('concept_bpm_repeatable_law', 'Tekrarlanabilir Yasaların')] her biri aktif: [GetLawType('law_repeatable_religion_promote_secular_values').GetName], [GetLawType('law_repeatable_culture_promote_democratic_values').GetName] ve [GetLawType('law_repeatable_culture_invite_foreign_experts').GetName]"
 BPM_VALUE_FROM_MODERNIZER_MINIMUM_BETWEEN_TWO_IDEOLOGIES:0 "$bpm_je_all_modernizers$ ve $bpm_je_all_antimodernizers$ arasındaki #bold en düşük#! Diyalektik Güç"
 BPM_VALUE_FROM_MODERNIZER_COPIED_SOCIETY_AMOUNT:0 "#bold $bpm_je_modernizers_copy_society_button$#! eyleminin daha önce kullanılma sayısı"
 BPM_VALUE_FROM_MODERNIZER_DIALECTIC_STRENGTH:0 "$bpm_je_all_modernizers$ için Diyalektik Güç"
 BPM_VALUE_FROM_ANTI_MODERNIZER_DIALECTIC_STRENGTH:0 "$bpm_je_all_antimodernizers$ için Diyalektik Güç"

 BPM_VALUE_FROM_ANTI_SECULAR_REACTION_LAW:0 "[GetLawType('law_repeatable_religion_anti_secular_reaction').GetName] [Concept('concept_bpm_repeatable_law', 'Tekrarlanabilir Yasası')] aktif"
 BPM_VALUE_FROM_PARADES_AND_DRILLS_LAW:0 "[GetLawType('law_repeatable_military_parades_and_drills').GetName] [Concept('concept_bpm_repeatable_law', 'Tekrarlanabilir Yasası')] aktif"
 BPM_VALUE_FROM_PROMOTE_ABSOLUTIST_VALUES_LAW:0 "[GetLawType('law_repeatable_culture_promote_absolutist_values').GetName] [Concept('concept_bpm_repeatable_law', 'Tekrarlanabilir Yasası')] aktif"
 BPM_VALUE_FROM_PROMOTE_STATE_RELIGION_LAW:0 "[GetLawType('law_repeatable_religion_promote_state_religion').GetName] [Concept('concept_bpm_repeatable_law', 'Tekrarlanabilir Yasası')] aktif"
 BPM_VALUE_FROM_PROMOTE_SECULAR_VALUES_LAW:0 "[GetLawType('law_repeatable_religion_promote_secular_values').GetName] [Concept('concept_bpm_repeatable_law', 'Tekrarlanabilir Yasası')] aktif"
 BPM_VALUE_FROM_PROMOTE_DEMOCRATIC_VALUES_LAW:0 "[GetLawType('law_repeatable_culture_promote_democratic_values').GetName] [Concept('concept_bpm_repeatable_law', 'Tekrarlanabilir Yasası')] aktif"
 BPM_VALUE_FROM_INVITE_FOREIGN_EXPERTS_LAW:0 "[GetLawType('law_repeatable_culture_invite_foreign_experts').GetName] [Concept('concept_bpm_repeatable_law', 'Tekrarlanabilir Yasası')] aktif"

 # SAVAŞ
 BPM_STABILITY_FROM_WAR_BASE:0 "#gold Devam Eden Savaş#! Temel Değeri"
 BPM_STABILITY_FROM_WAR_OCCUPATION:0 "#gold Devam Eden Savaş#! Düşman İşgali"
 BPM_STABILITY_FROM_WAR_CASUALTIES:0 "#gold Devam Eden Savaş#! Kayıplar"