l_simp_chinese:
 BPM_VALUE_BASE:0 "基础值"
 BPM_VALUE_FROM_LAW_MONARCHY:0 "[GetLawType('law_monarchy').GetName][Concept('concept_law', '法律')]"
 BPM_VALUE_FROM_LAW_TRADITIONALISM:0 "[GetLawType('law_traditionalism').GetName][Concept('concept_law', '法律')]"
 BPM_VALUE_FROM_LAW_PEASANT_LEVIES:0 "[GetLawType('law_peasant_levies').GetName][Concept('concept_law', '法律')]"
 BPM_VALUE_FROM_LAW_SERFDOM:0 "[GetLawType('law_serfdom').GetName][Concept('concept_law', '法律')]"
 BPM_VALUE_FROM_LAW_TENANT_FARMERS:0 "[GetLawType('law_tenant_farmers').GetName][Concept('concept_law', '法律')]"
 BPM_VALUE_FROM_LAW_ISOLATIONISM:0 "[GetLawType('law_isolationism').GetName][Concept('concept_law', '法律')]"
 BPM_VALUE_FROM_LAW_NO_ELECTIONS:0 "无[Concept('concept_election', '选举')][Concept('concept_law', '法律')]"
 BPM_VALUE_FROM_INSTITUTION_NATIONAL_GUARD:0 "[GetLawType('law_national_guard').GetName][Concept('concept_institution', '机构')]投入等级"
 BPM_VALUE_FROM_INSTITUTION_SECRET_POLICE:0 "[GetLawType('law_secret_police').GetName][Concept('concept_institution', '机构')]投入等级"
 BPM_VALUE_FROM_LAW_OUTLAWED_DISSENT:0 "[GetLawType('law_outlawed_dissent').GetName][Concept('concept_law', '法律')]"
 BPM_VALUE_FROM_LAW_CENSORSHIP:0 "[GetLawType('law_censorship').GetName][Concept('concept_law', '法律')]"
 BPM_VALUE_FROM_LAW_PROTECTED_SPEECH:0 "[GetLawType('law_protected_speech').GetName][Concept('concept_law', '法律')]"
 BPM_VALUE_FROM_LAW_ANARCHY:0 "[GetLawType('law_anarchy').GetName][Concept('concept_law', '法律')]"
 BPM_VALUE_FROM_INSTITUTION_GUARANTEED_LIBERTIES:0 "[GetLawType('law_guaranteed_liberties').GetName][Concept('concept_institution', '机构')]投入等级"
 BPM_VALUE_FROM_RADICALS:0 "[Concept('concept_radical', '激进派')]"
 BPM_VALUE_FROM_LOYALISTS:0 "[Concept('concept_loyalist', '效忠派')]"
 BPM_VALUE_FROM_WAR:0 "[Concept('concept_war_support', '战争支持度')]"
 BPM_VALUE_FROM_REVOLUTION:0 "进行中的[Concept('concept_revolution', '革命')]"
 BPM_VALUE_FROM_INSURRECTION:0 "暴动[Concept('concept_interest_group', '利益集团')]"
 BPM_VALUE_FROM_ELECTION:0 "进行中的[Concept('concept_revolution', '选举')]"
 BPM_VALUE_FROM_LOW_LEGITIMACY:0 "[Concept('concept_legitimacy', '合法性')]低（低于30）"
 BPM_VALUE_FROM_VERY_LOW_LEGITIMACY:0 "[Concept('concept_legitimacy', '合法性')]极低（低于10）"
 BPM_VALUE_FROM_ENTRENCHED_INTEREST_GROUPS:0 "每年执政[Concept('concept_interest_group', '利益集团')]统治花费"
 BPM_VALUE_FROM_NO_TECH_MASS_COMMS:0 "未研究大众传播[Concept('concept_technology', '科技')]"
 BPM_VALUE_FROM_LAW_AD_HOC_CENTRALIZATION:0 "[GetLawType('law_ad_hoc_centralization').GetName][Concept('concept_law', '法律')]"
 BPM_VALUE_FROM_INSTITUTION_LOCAL_POLICE:0 "[GetLawType('law_local_police').GetName][Concept('concept_institution', '机构')]投入等级"
 BPM_VALUE_FROM_INSTITUTION_NATIONAL_POLICE:0 "[GetLawType('law_dedicated_police').GetName][Concept('concept_institution', '机构')]投入等级"
 BPM_VALUE_FROM_INSTITUTION_MILITARIZED_POLICE:0 "[GetLawType('law_militarized_police').GetName][Concept('concept_institution', '机构')]投入等级"
 BPM_VALUE_FROM_INSTITUTION_ELECTED_POLICE:0 "[GetLawType('law_elected_police').GetName][Concept('concept_institution', '机构')]投入等级"
 BPM_VALUE_FROM_INSTITUTION_SUFFRAGE:0 "[GetInstitutionType('institution_suffrage').GetName][Concept('concept_institution', '机构')]投入等级"
 BPM_VALUE_FROM_WAR_HIGH_SUPPORT:0 "[Concept('concept_war_support', '战争支持度')]高"
 BPM_VALUE_FROM_WAR_MEDIUM_SUPPORT:0 "[Concept('concept_war_support', '战争支持度')]中"
 BPM_VALUE_FROM_WAR_LOW_SUPPORT:0 "[Concept('concept_war_support', '战争支持度')]低"
 BPM_VALUE_FROM_WAR_VERY_LOW_SUPPORT:0 "[Concept('concept_war_support', '战争支持度')]极低"
 BPM_STABILITY_FROM_WAR_BASE:0 "#gold 进行中的战争#!基础值"
 BPM_STABILITY_FROM_WAR_OCCUPATION:0 "#gold 进行中的战争#!敌军占领"
 BPM_STABILITY_FROM_WAR_CASUALTIES:0 "#gold 进行中的战争#!伤亡"