l_simp_chinese:
 BPM_VALUE_BASE:0 "基础值"
 BPM_VALUE_RANDOM:0 "随机值"
 BPM_VALUE_FROM_NO_TECH_MASS_COMMS:0 "没有大众传播[Concept('concept_technology', '科技')]"
 BPM_VALUE_FROM_LAW_MONARCHY:0 "[Concept('concept_law', '法律')][GetLawType('law_monarchy').GetName]"
 BPM_VALUE_FROM_LAW_TRADITIONALISM:0 "[Concept('concept_law', '法律')][GetLawType('law_traditionalism').GetName]"
 BPM_VALUE_FROM_LAW_AGRARIANISM:0 "[Concept('concept_law', '法律')][GetLawType('law_agrarianism').GetName]"
 BPM_VALUE_FROM_LAW_LAISSEZ_FAIRE:0 "[Concept('concept_law', '法律')][GetLawType('law_laissez_faire').GetName]"
 BPM_VALUE_FROM_LAW_INTERVENTIONISM:0 "[Concept('concept_law', '法律')][GetLawType('law_interventionism').GetName]"
 BPM_VALUE_FROM_LAW_HOMESTEADING:0 "[Concept('concept_law', '法律')][GetLawType('law_homesteading').GetName]"
 BPM_VALUE_FROM_LAW_PEASANT_LEVIES:0 "[Concept('concept_law', '法律')][GetLawType('law_peasant_levies').GetName]"
 BPM_VALUE_FROM_LAW_SERFDOM:0 "[Concept('concept_law', '法律')][GetLawType('law_serfdom').GetName]"
 BPM_VALUE_FROM_LAW_TENANT_FARMERS:0 "[Concept('concept_law', '法律')][GetLawType('law_tenant_farmers').GetName]"
 BPM_VALUE_FROM_LAW_COMMERCIALIZED_AGRICULTURE:0 "[Concept('concept_law', '法律')][GetLawType('law_commercialized_agriculture').GetName]"
 BPM_VALUE_FROM_LAW_ISOLATIONISM:0 "[Concept('concept_law', '法律')][GetLawType('law_isolationism').GetName]"
 BPM_VALUE_FROM_LAW_UNREGULATED_WORK_TIME:0 "[Concept('concept_law', '法律')][GetLawType('law_unregulated_work_time').GetName]"
 BPM_VALUE_FROM_LAW_NO_WORKERS_RIGHTS:0 "[Concept('concept_law', '法律')][GetLawType('law_no_workers_rights').GetName]"
 BPM_VALUE_FROM_LAW_NO_WELFARE:0 "[Concept('concept_law', '法律')][GetLawType('law_no_social_security').GetName]"
 BPM_VALUE_FROM_LAW_POOR_LAWS:0 "[Concept('concept_law', '法律')][GetLawType('law_poor_laws').GetName]"
 BPM_VALUE_FROM_LAW_NO_ELECTIONS:0 "[Concept('concept_law', '法律')]没有[Concept('concept_election', '选举')]"
 BPM_VALUE_FROM_LAW_NO_FULL_DEMOCRACY:0 "[Concept('concept_law', '法律')]没有投资满额选举权的[GetLawType('law_universal_suffrage').GetName]"
 BPM_VALUE_FROM_LAW_OUTLAWED_DISSENT:0 "[Concept('concept_law', '法律')][GetLawType('law_outlawed_dissent').GetName]"
 BPM_VALUE_FROM_LAW_SOCIALIST_BAN:0 "[Concept('concept_law', '法律')][GetLawType('law_party_anti_socialist').GetName]"
 BPM_VALUE_FROM_LAW_CENSORSHIP:0 "[Concept('concept_law', '法律')][GetLawType('law_censorship').GetName]"
 BPM_VALUE_FROM_LAW_TRADITIONAL_OSTRACISM:0 "[Concept('concept_law', '法律')][GetLawType('law_traditional_ostracism').GetName]"
 BPM_VALUE_FROM_RIGHT_WING_APPROVAL:0 "来自[Concept('concept_bpm_ig_is_right_wing', '右翼利益集团')]的[concept_clout]和[concept_approval]"
 BPM_VALUE_FROM_LAW_PROTECTED_SPEECH:0 "[Concept('concept_law', '法律')][GetLawType('law_protected_speech').GetName]"
 BPM_VALUE_FROM_LAW_ANARCHY:0 "[Concept('concept_law', '法律')][GetLawType('law_anarchy').GetName]"
 BPM_VALUE_FROM_LAW_AD_HOC_CENTRALIZATION:0 "[Concept('concept_law', '法律')][GetLawType('law_ad_hoc_centralization').GetName]"
 BPM_VALUE_FROM_LAW_STATE_RELIGION:0 "[Concept('concept_law', '法律')][GetLawType('law_state_religion').GetName]"
 BPM_VALUE_FROM_LAW_STATE_ATHEISM:0 "[Concept('concept_law', '法律')][GetLawType('law_state_atheism').GetName]"
 BPM_VALUE_FROM_LAW_NO_MULTICULTURALISM:0 "[Concept('concept_law', '法律')]没有[GetLawType('law_multicultural').GetName]"
 BPM_VALUE_FROM_INSTITUTION_LOCAL_POLICE:0 "对[GetLawType('law_local_police').GetName]的[Concept('concept_institution', '制度')]投资"
 BPM_VALUE_FROM_INSTITUTION_NATIONAL_POLICE:0 "对[GetLawType('law_dedicated_police').GetName]的[Concept('concept_institution', '制度')]投资"
 BPM_VALUE_FROM_INSTITUTION_MILITARIZED_POLICE:0 "对[GetLawType('law_militarized_police').GetName]的[Concept('concept_institution', '制度')]投资"
 BPM_VALUE_FROM_INSTITUTION_ELECTED_POLICE:0 "对[GetLawType('law_elected_police').GetName]的[Concept('concept_institution', '制度')]投资"
 BPM_VALUE_FROM_INSTITUTION_NATIONAL_GUARD:0 "对[GetLawType('law_national_guard').GetName]的[Concept('concept_institution', '制度')]投资"
 BPM_VALUE_FROM_INSTITUTION_SECRET_POLICE:0 "对[GetLawType('law_secret_police').GetName]的[Concept('concept_institution', '制度')]投资"
 BPM_VALUE_FROM_INSTITUTION_GUARANTEED_LIBERTIES:0 "对[GetLawType('law_guaranteed_liberties').GetName]的[Concept('concept_institution', '制度')]投资"
 BPM_VALUE_FROM_INSTITUTION_SUFFRAGE:0 "对[GetInstitutionType('institution_suffrage').GetName]的[Concept('concept_institution', '制度')]投资"
 BPM_VALUE_FROM_INSTITUTION_CENSORSHIP:0 "对[GetLawType('law_censorship').GetName]的[Concept('concept_institution', '制度')]投资"
 BPM_VALUE_FROM_INSTITUTION_OUTLAWED_DISSENT:0 "对[GetLawType('law_outlawed_dissent').GetName]的[Concept('concept_institution', '制度')]投资"
 BPM_VALUE_FROM_INSTITUTION_RIGHT_OF_ASSEMBLY:0 "对[GetLawType('law_right_of_assembly').GetName]的[Concept('concept_institution', '制度')]投资"
 BPM_VALUE_FROM_REPEATABLE_LAW_POLITICS_TERROR:0 "[Concept('concept_bpm_repeatable_law', '$concept_bpm_repeatable_law$')][GetLawType('law_repeatable_politics_great_terror').GetName]"
 BPM_VALUE_FROM_RADICALS:0 "[Concept('concept_radical', '激进派')]"
 BPM_VALUE_FROM_LOYALISTS:0 "[Concept('concept_loyalist', '忠诚派')]"
 BPM_VALUE_FROM_WAR:0 "[Concept('concept_war_support', '战争支持度')]"
 BPM_VALUE_FROM_WAR_HIGH_SUPPORT:0 "高[Concept('concept_war_support', '战争支持度')]"
 BPM_VALUE_FROM_WAR_MEDIUM_SUPPORT:0 "中[Concept('concept_war_support', '战争支持度')]"
 BPM_VALUE_FROM_WAR_LOW_SUPPORT:0 "低[Concept('concept_war_support', '战争支持度')]"
 BPM_VALUE_FROM_WAR_VERY_LOW_SUPPORT:0 "极低[Concept('concept_war_support', '战争支持度')]"
 BPM_VALUE_FROM_REVOLUTION:0 "进行中的[Concept('concept_revolution', '革命')]"
 BPM_VALUE_FROM_INSURRECTION:0 "酝酿中的[Concept('concept_revolution', '革命')]"
 BPM_VALUE_FROM_INSURRECTION_CLOUT:0 "起义性[concept_interest_group]的[concept_clout]"
 BPM_VALUE_FROM_ELECTION:0 "进行中的[Concept('concept_election', '选举')]"
 BPM_VALUE_FROM_LOW_LEGITIMACY:0 "低（低于30）[Concept('concept_legitimacy', '合法性')]"
 BPM_VALUE_FROM_VERY_LOW_LEGITIMACY:0 "极低（低于10）[Concept('concept_legitimacy', '合法性')]"
 BPM_VALUE_FROM_ENTRENCHED_INTEREST_GROUPS:0 "当前执政[Concept('concept_interest_group', '利益集团')]每[concept_in_government]一年"
 BPM_VALUE_FROM_RIGIDITY:0 "[Concept('concept_bpm_political_stability', '$concept_bpm_political_stability$')]"
 BPM_VALUE_FROM_PEASANT_POPULATION:0 "[GetPopType('peasants').GetName]人口"
 BPM_VALUE_FROM_LABORER_POPULATION:0 "[GetPopType('laborers').GetName]人口"
 BPM_VALUE_FROM_MACHINIST_POPULATION:0 "[GetPopType('machinists').GetName]"
 BPM_VALUE_FROM_PEASANT_RADICALS:0 "来自[concept_radical][GetPopType('peasants').GetName]"
 BPM_VALUE_FROM_LABORER_RADICALS:0 "来自[concept_radical][GetPopType('laborers').GetName]"
 BPM_VALUE_FROM_MACHINIST_RADICALS:0 "来自[concept_radical][GetPopType('machinists').GetName]"
 BPM_VALUE_FROM_LABORER_LOYALISTS:0 "来自[concept_loyalist][GetPopType('laborers').GetName]"
 BPM_VALUE_FROM_MACHINIST_LOYALISTS:0 "来自[concept_loyalist][GetPopType('machinists').GetName]"
 BPM_VALUE_FROM_SYNDICALISM_DEVELOPMENT:0 "#yellow $je_bpm_syndicalism$#!日志条目进度"
 BPM_VALUE_FROM_AGRARIAN_SOCIALISM_DEVELOPMENT:0 "#yellow $je_bpm_agrarian_socialism$#!日志条目进度"
 BPM_VALUE_FROM_SOCS_POPULARITY:0 "来自[GetInterestGroupVariant('ig_socialists', GetPlayer).GetName]人气"
 BPM_VALUE_FROM_REVSOCS_POPULARITY:0 "来自[GetInterestGroupVariant('ig_revolutionist_socialists', GetPlayer).GetName]人气"
 BPM_VALUE_FROM_REFSOCS_POPULARITY:0 "来自[GetInterestGroupVariant('ig_reformist_socialists', GetPlayer).GetName]人气"
 BPM_VALUE_FROM_TRADE_UNIONS_POPULARITY:0 "来自[GetInterestGroupVariant('ig_trade_unions', GetPlayer).GetName]人气"
 BPM_VALUE_FROM_RURAL_FOLK_POPULARITY:0 "来自[GetInterestGroupVariant('ig_rural_folk', GetPlayer).GetName]人气"
 BPM_VALUE_FROM_INTELLIGENTSIA_POPULARITY:0 "来自[GetInterestGroupVariant('ig_intelligentsia', GetPlayer).GetName]人气"
 BPM_VALUE_FROM_NATLIBS_POPULARITY:0 "来自[GetInterestGroupVariant('ig_national_liberals', GetPlayer).GetName]人气"
 BPM_VALUE_FROM_LIBS_POPULARITY:0 "来自[GetInterestGroupVariant('ig_liberals', GetPlayer).GetName]人气"
 BPM_VALUE_FROM_INDUSTRIALISTS_POPULARITY:0 "来自[GetInterestGroupVariant('ig_industrialists', GetPlayer).GetName]人气"
 BPM_VALUE_FROM_PETTY_BOURGEOISIE_POPULARITY:0 "来自[GetInterestGroupVariant('ig_petty_bourgeoisie', GetPlayer).GetName]人气"
 BPM_VALUE_FROM_ARMED_FORCES_POPULARITY:0 "来自[GetInterestGroupVariant('ig_armed_forces', GetPlayer).GetName]人气"
 BPM_VALUE_FROM_RADS_POPULARITY:0 "来自[GetInterestGroupVariant('ig_radicals', GetPlayer).GetName]人气"
 BPM_VALUE_FROM_REC:0 "来自非裔美国人对坚定派的支持"
 BPM_VALUE_POWERFUL_ANARCHISTS:0 "强大的无政府主义者"
 BPM_VALUE_BOLSTERED_ANARCHISTS:0 "受扶植的无政府主义者"
 BPM_VALUE_ANARCHIST_AGITATORS:0 "无政府主义[Concept('concept_agitator', '煽动者')]"
 BPM_VALUE_FROM_MONARCH_POPULARITY:0 "[Concept('concept_ruler', '君主')][Concept('concept_popularity', '人气')]（[GetPlayer.GetRuler.GetFullName]）"
 BPM_VALUE_FROM_MONARCH_POPULARITY_NEGATIVE:0 "负面的[Concept('concept_ruler', '君主')][Concept('concept_popularity', '人气')]（[GetPlayer.GetRuler.GetFullName]）"
 BPM_VALUE_FROM_N_LEADER_AND_AGITATORS:0 "以下[Concept('concept_leader', '领袖')]与[Concept('concept_agitator', '煽动者')]的[Concept('concept_popularity', '人气')]："
 BPM_VALUE_FROM_CONSERVATIVE_LEADER_AND_AGITATORS:0 "$BPM_VALUE_FROM_N_LEADER_AND_AGITATORS$[GetInterestGroupVariant('ig_conservatives',GetPlayer).GetName]"
 BPM_VALUE_FROM_REACTIONARY_LEADER_AND_AGITATORS:0 "$BPM_VALUE_FROM_N_LEADER_AND_AGITATORS$[GetInterestGroupVariant('ig_reactionaries',GetPlayer).GetName]"
 BPM_VALUE_FROM_LIBERAL_LEADER_AND_AGITATORS:0 "$BPM_VALUE_FROM_N_LEADER_AND_AGITATORS$[GetInterestGroupVariant('ig_liberals',GetPlayer).GetName]"
 BPM_VALUE_FROM_RADICAL_LEADER_AND_AGITATORS:0 "$BPM_VALUE_FROM_N_LEADER_AND_AGITATORS$[GetInterestGroupVariant('ig_radicals',GetPlayer).GetName]"
 BPM_VALUE_FROM_SOCIALIST_LEADER_AND_AGITATORS:0 "$BPM_VALUE_FROM_N_LEADER_AND_AGITATORS$[GetInterestGroupVariant('ig_socialists',GetPlayer).GetName]"
 BPM_VALUE_FROM_AGRARIAN_SOCIALIST_CHARACTERS:0 "来自[GetIdeology('ideology_eco_agrarian_socialist').GetName]人物"
 BPM_VALUE_FROM_SYNDICALIST_CHARACTERS:0 "来自[GetIdeology('ideology_dop_syndicalist').GetName]人物"
 BPM_VALUE_FROM_JOURNAL_PROGRESS:0 "日志条目进度"
 BPM_VALUE_JOURNAL_DURATION:0 "日志条目持续时间"
 BPM_VALUE_FROM_PREV_BOMBS:0 "来自先前的爆炸事件"
 BPM_VALUE_FROM_POTD_CONVICTION:0 "来自#pink 信念强度#!"
 BPM_VALUE_POTD_ENDED_IN_GP:0 "#N 行动宣传#!在一个[concept_great_power]中终结"
 BPM_VALUE_FROM_SYNDICALISM_LEGITIMIZED:0 "合法化的工团主义"
 BPM_VALUE_FROM_FAILED_SYNDICALIST_STRIKES:0 "来自失败的工团主义罢工"
 BPM_VALUE_FROM_NO_TECH_ANARCHISM:0 "未研究#yellow $anarchism$#!"
 BPM_VALUE_FROM_SOCIALIST_IGS_POPULARITY:0 "[Concept('concept_bpm_ig_is_socialist','社会主义利益集团')]人口"
 BPM_VALUE_FROM_SOCIALISTS_APPROVAL_POPULARITY:0 "[Concept('concept_bpm_ig_is_socialist','社会主义利益集团')]人口与[Concept('concept_approval','不满')]"
 BPM_VALUE_FROM_TRADE_UNION_POPULARITY:0 "[GetInterestGroupVariant('ig_trade_unions', GetPlayer).GetName]人口"
 BPM_VALUE_FROM_TRADE_UNIONS_APPROVAL_POPULARITY:0 "[GetInterestGroupVariant('ig_trade_unions', GetPlayer).GetName]人口与[Concept('concept_approval','不满')]"
 BPM_VALUE_FROM_TRADE_UNION_CLOUT:0 "[GetInterestGroupVariant('ig_trade_unions', GetPlayer).GetName]的[concept_clout]"
 BPM_VALUE_FROM_TRADE_UNIONS_APPROVAL_CLOUT:0 "[GetInterestGroupVariant('ig_trade_unions', GetPlayer).GetName]的[concept_clout]与[Concept('concept_approval','不满')]"
 BPM_VALUE_FROM_POPULAR_ANGRY_TRADE_UNIONS:0 "$ig_approval_angry$[GetInterestGroupVariant('ig_trade_unions', GetPlayer).GetName]"
 BPM_VALUE_FROM_ONGOING_LIBERAL_REVOLUTION:0 "进行中的[concept_bpm_ig_is_liberal][concept_revolution]"
 BPM_VALUE_FROM_ONGOING_SOCIALIST_REVOLUTION:0 "进行中的[concept_bpm_ig_is_socialist][concept_revolution]"
 BPM_VALUE_FROM_law_corporatized_unions:0 "[GetLawType('law_corporatized_unions').GetName]"
 BPM_VALUE_FROM_law_anti_strike_laws:0 "[GetLawType('law_anti_strike_laws').GetName]"
 BPM_VALUE_REVOLUTIONIST_SOCIALISTS_IN_GOVERNMENT:0 "[GetInterestGroupVariant('ig_revolutionist_socialists', GetPlayer).GetName][concept_in_government]"
 BPM_VALUE_REFORMIST_SOCIALISTS_IN_GOVERNMENT:0 "[GetInterestGroupVariant('ig_reformist_socialists', GetPlayer).GetName][concept_in_government]"
 BPM_VALUE_SOCIALISTS_IN_GOVERNMENT:0 "[GetInterestGroupVariant('ig_socialists', GetPlayer).GetName][concept_in_government]"
 BPM_VALUE_STRIKE_EXHAUSTION:0 "罢工者的#blue 疲惫程度#!"
 BPM_VALUE_FROM_NO_GOAL:0 "罢工没有目标"
 BPM_VALUE_FROM_CONTENT_LABOR_IGS:0 "一个或多个[Concept('concept_bpm_ig_is_labor', '劳工利益集团')]持有正面[concept_approval]"
 BPM_MAX_EXHAUSTION_RATE_IN_REVOLUTION:0 "#blue 疲惫#!速率在活跃的[concept_revolution]中被设上限"
 BPM_VALUE_FROM_RETREATING_STRIKERS:0 "#P 罢工者正在撤退！#!"
 BPM_VALUE_FROM_PRO_CONSERVATIVE_LAW_PASSING:0 "自本日志条目开始以来通过的[GetInterestGroupVariant('ig_conservatives', GetPlayer).GetName]偏好[Concept('concept_law', '法律')]"
 BPM_VALUE_FROM_PRO_MODERNIZER_LOBBY_APPEASEMENT:0 "对$bpm_je_all_modernizers$所偏好的[Concept('concept_political_lobby', '政治游说团体')]的[Concept('concept_political_lobby_appeasement', '安抚')]"
 BPM_VALUE_FROM_PRO_MODERNIZER_LAW_PASSING:0 "自本日志条目开始以来通过的[GetInterestGroupVariant('ig_liberals', GetPlayer).GetName]或[GetInterestGroupVariant('ig_radicals', GetPlayer).GetName]偏好[Concept('concept_law', '法律')]"
 BPM_VALUE_FROM_PRO_CONSERVATIVE_REPEATABLE_LAWS:0 "以下[Concept('concept_bpm_repeatable_law', '可重复法律')]当前生效：[GetLawType('law_repeatable_religion_anti_secular_reaction').GetName]、[GetLawType('law_repeatable_military_parades_and_drills').GetName]、[GetLawType('law_repeatable_culture_promote_absolutist_values').GetName]和[GetLawType('law_repeatable_religion_promote_state_religion').GetName]"
 BPM_VALUE_FROM_PRO_LIBERAL_REPEATABLE_LAWS:0 "以下[Concept('concept_bpm_repeatable_law', '可重复法律')]每项生效：[GetLawType('law_repeatable_religion_promote_secular_values').GetName]、[GetLawType('law_repeatable_culture_promote_democratic_values').GetName]和[GetLawType('law_repeatable_culture_invite_foreign_experts').GetName]"
 BPM_VALUE_FROM_MODERNIZER_MINIMUM_BETWEEN_TWO_IDEOLOGIES:0 "$bpm_je_all_modernizers$与$bpm_je_all_antimodernizers$之间#bold 较低#!的辩证强度"
 BPM_VALUE_FROM_MODERNIZER_COPIED_SOCIETY_AMOUNT:0 "此前使用#bold $bpm_je_modernizers_copy_society_button$#!行动的次数"
 BPM_VALUE_FROM_MODERNIZER_DIALECTIC_STRENGTH:0 "$bpm_je_all_modernizers$的辩证强度"
 BPM_VALUE_FROM_ANTI_MODERNIZER_DIALECTIC_STRENGTH:0 "$bpm_je_all_antimodernizers$的辩证强度"
 BPM_VALUE_FROM_ANTI_SECULAR_REACTION_LAW:0 "[GetLawType('law_repeatable_religion_anti_secular_reaction').GetName][Concept('concept_bpm_repeatable_law', '可重复法律')]生效"
 BPM_VALUE_FROM_PARADES_AND_DRILLS_LAW:0 "[GetLawType('law_repeatable_military_parades_and_drills').GetName][Concept('concept_bpm_repeatable_law', '可重复法律')]生效"
 BPM_VALUE_FROM_PROMOTE_ABSOLUTIST_VALUES_LAW:0 "[GetLawType('law_repeatable_culture_promote_absolutist_values').GetName][Concept('concept_bpm_repeatable_law', '可重复法律')]生效"
 BPM_VALUE_FROM_PROMOTE_STATE_RELIGION_LAW:0 "[GetLawType('law_repeatable_religion_promote_state_religion').GetName][Concept('concept_bpm_repeatable_law', '可重复法律')]生效"
 BPM_VALUE_FROM_PROMOTE_SECULAR_VALUES_LAW:0 "[GetLawType('law_repeatable_religion_promote_secular_values').GetName][Concept('concept_bpm_repeatable_law', '可重复法律')]生效"
 BPM_VALUE_FROM_PROMOTE_DEMOCRATIC_VALUES_LAW:0 "[GetLawType('law_repeatable_culture_promote_democratic_values').GetName][Concept('concept_bpm_repeatable_law', '可重复法律')]生效"
 BPM_VALUE_FROM_INVITE_FOREIGN_EXPERTS_LAW:0 "[GetLawType('law_repeatable_culture_invite_foreign_experts').GetName][Concept('concept_bpm_repeatable_law', '可重复法律')]生效"
 BPM_STABILITY_FROM_WAR_BASE:0 "#gold 进行中的战争#!基础值"
 BPM_STABILITY_FROM_WAR_OCCUPATION:0 "#gold 进行中的战争#!敌方占领"
 BPM_STABILITY_FROM_WAR_CASUALTIES:0 "#gold 进行中的战争#!伤亡"
