permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      type:
        description: "Version fragment (patch, minor, major)"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: patch
      branch:
        description: "Branch to release from"
        required: true
        default: "main"
      notify-discord:
        description: "Notify Discord about the release"
        required: true
        type: boolean
        default: true
      workshop:
        description: "Publish to Steam Workshop"
        required: true
        type: boolean
        default: true

jobs:
  release:
    name: "Publish Release"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch }}

      - name: Checkout Tags
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch --prune --tags

      - name: Get Version
        id: project
        uses: actions-ecosystem/action-get-latest-tag@v1

      - name: Increment Version
        id: increment-version
        uses: christian-draeger/increment-semantic-version@1.2.1
        with:
          current-version: ${{ steps.project.outputs.tag }}
          version-fragment: ${{ inputs.type }}


      - name: Collect Changes
        id: commits
        run: |
          {
            echo 'markdown<<EOF'
            echo "$(git log ${{ steps.project.outputs.tag }}..HEAD --no-merges --pretty=format:' - %s (@%an)')"
            echo EOF
          } >> "$GITHUB_OUTPUT"
          echo "# Commits" >> $GITHUB_STEP_SUMMARY
          echo "$(git log ${{ steps.project.outputs.tag }}..HEAD --no-merges --pretty=format:' - %s')" >> $GITHUB_STEP_SUMMARY

      - name: Publish GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          tag_name: ${{ steps.increment-version.outputs.next-version }}
          release_name: ${{ steps.increment-version.outputs.next-version }}
          body: |
            New version of **BPM**.

            ### Commits:
            ${{ steps.commits.outputs.markdown }}

      - name: Setup SteamCMD
        uses: buildalon/setup-steamcmd@v1.0.4

      - name: Publish to Workshop
        if: ${{ inputs.workshop }}
        shell: bash
        run: |
          ./update_bpm.sh better_politics_mod '${{ secrets.STEAM_PASSWORD }}'

      - name: Notify Discord
        if: ${{ inputs.notify-discord }}
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: |
            <@&1271322512063594547>
            New **BPM** ${{ inputs.type }} version released: ${{ steps.increment-version.outputs.next-version }}.
            [Steam](<https://steamcommunity.com/sharedfiles/filedetails/?id=2932134122>)        [GitHub](<https://github.com/Better-Politics-Mod/Better-Politics-Mod-Vic-3/releases/tag/${{ steps.increment-version.outputs.next-version }}>)
            ${{ steps.commits.outputs.markdown }}