name: Validation
permissions:
  contents: read
  packages: write
  checks: write

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # If your repository uses lfs include this property
        with:
          lfs: 'true'

      - name: Checkout Validation
        uses: actions/checkout@v4
        with:
          repository: xxxAnn/tiger-action-repository
          ref: 'main'
          path: 'validation'
          # Validation token defined in the usage instructions
          token: ${{ secrets.VALIDATION_TOKEN }}

      - name: Validate
        uses: ./validation/
        with:
          # Relative path to the mod directory from repository root (defaults to repository root directory)
          mod-directory: 'better-politics-mod'
          # Relative path to the validation action repository root (defaults to repository root directory)
          action-directory: 'validation'
          # Which game files should be used for validation (ck3 or vic3 but defaults to vic3) 
          game: 'vic3'
          update-tiger: true